version: '3.8'

services:
  postgres:
    image: postgres:15.3
    user: postgres
    command: -c jit=off
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: next-example
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 20
    volumes:
      - next-example-postgres:/var/lib/postgresql/data
    networks:
      - next-example-network

  rabbitmq:
    image: rabbitmq:3.10.5-management
    user: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 1s
      timeout: 5s
      retries: 20
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    networks:
      - next-example-network

networks:
  next-example-network:

volumes:
  next-example-postgres:
